#!/bin/sh

# Writes version constants to the path given as $1. Defaults to
# src/cli/version.rs for direct/manual invocation; build.rs passes an
# $OUT_DIR path so the file lands in build output.
#
# Works both in a normal git clone AND in a cargo git-DEPENDENCY checkout, which
# has no .git directory. There `git rev-parse` fails, so we fall back to the
# cargo-provided package version instead of aborting. (Previously `set -e` made the
# first failing git call exit before version.rs was written, so build.rs's include!
# of it failed the *consumer's* build — jetpack was unusable as a git dependency.)
out="${1:-src/cli/version.rs}"

if head=$(git rev-parse HEAD 2>/dev/null); then
    branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
else
    head="${CARGO_PKG_VERSION:-unknown}"
    branch="release"
fi
date=$(date)

{
    echo "// auto generated by version.sh"
    echo "pub const GIT_VERSION: &str = \"$head\";"
    echo "pub const GIT_BRANCH: &str = \"$branch\";"
    echo "pub const BUILD_TIME: &str = \"$date\";"
} > "$out"
